PracticeControllerViews/Models/ErrorViewModel.cs
namespace PracticeControllerViews.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PracticeControllerViews/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeControllerViews.Models;
using System.Diagnostics;

namespace PracticeControllerViews.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PracticeControllerViews/Controllers/PracticeRazorSyntaxController.cs
using Microsoft.AspNetCore.Mvc;

namespace PracticeControllerViews.Controllers
{
    public class PracticeRazorSyntaxController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PracticeControllerViews/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticeControllerViews/Views/PracticeRazorSyntax/Index.cshtml
@using PracticeControllerViews.Repo

@*Razor syntax:
Razor supports C# and uses the @ symbol to transition from HTML to C#. Razor evaluates C# expressions and renders them in the HTML output.*@

@{
    string message = "foreignObject example with Scalable Vector Graphics (SVG)";
}

<svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="0" rx="10" ry="10" width="200" height="200" stroke="black" 
        fill="none" />
    <foreignObject x="20" y="20" width="160" height="160">
        <p>@message</p>
    </foreignObject>
</svg>

@*Implicit Razor expressions start with @ followed by C# code:*@
<p>@DateTime.Now</p>
<p>@DateTime.IsLeapYear(2016)</p>

@*Implicit expressions cannot contain C# generics, as the characters inside the brackets (<>) are interpreted as an HTML tag. 
The following code is not valid:*@
@*<p>@await DoSomething("hello", "world")</p>*@



@*Explicit Razor expressions
Explicit Razor expressions consist of an @ symbol with balanced parenthesis. 
To render last week's time, the following Razor markup is used:*@

<p>Last week this time: @(DateTime.Now - TimeSpan.FromDays(7))</p>
@*Any content within the @() parenthesis is evaluated and rendered to the output.
Implicit expressions, described in the previous section, generally can't contain spaces.*@


@*Explicit expressions can be used to concatenate text with an expression result:*@
@*Explicit expressions can be used to render output from generic methods in .cshtml files. *@

@{
    var joe = new Person("Joe", 33);
}

<p>Age: @(joe.Age)</p>


@("<span>Hello World</span>")
@Html.Raw("<span>Hello World</span>")


@*Razor code blocks
Razor code blocks start with @ and are enclosed by {}. Unlike expressions, C# code inside code blocks isn't rendered. 
Code blocks and expressions in a view share the same scope and are defined in order:*@

@{
    var quote = "The future depends on what you do today. - Mahatma Gandhi";
}

<p>@quote</p>

@{
    quote = "Hate cannot drive out hate, only love can do that. - Martin Luther King, Jr.";
}

<p>@quote</p>

@*In code blocks, local functions with markup can also declared to serve as templating methods:*@

@{
    void RenderName(string name)
    {
    <p>Name: <strong>@name</strong></p>
    }

    RenderName("Mahatma Gandhi");
    RenderName("Martin Luther King, Jr.");
}

@*    Implicit transitions
The default language in a code block is C#, but the Razor Page can transition back to HTML:*@
@{
    var inCSharp = true;
    <p>Now in HTML, was in C# @inCSharp</p>
}

@*Explicit delimited transition
To define a subsection of a code block that should render HTML, surround the characters for rendering with the Razor <text> tag:

The <text> tag is useful to control whitespace when rendering content:

Only the content between the <text> tag is rendered.
No whitespace before or after the <text> tag appears in the HTML output.
*@

@{
    string[] people = { "Hemant", "Rahul", "Mayank" };
}
@for (var i = 0; i < people.Length; i++)
{
    var person = people[i];
    <text>      Name: @person,</text>
}

@*Explicit line transition
To render the rest of an entire line as HTML inside a code block, use @: syntax:*@

@for (var i = 0; i < people.Length; i++)
{
    var person = people[i];
    @:Name: @person,
}

@*
Conditionals @if, else if, else, and @switch*@

@{
    var value = 100;
}
@if (value % 2 == 0)
{
    <p>The value was even.</p>
}
else if (value >= 1337)
{
    <p>The value is large.</p>
}
else
{
    <p>The value is odd and small.</p>
}


 @*   Looping @for, @foreach, @while, and @do while
 Templated HTML can be rendered with looping control statements. To render a list of people:
 *@



@for (var i = 0; i < people.Length; i++)
{
    var person = people[i];
    @:Name: @person,
}

@*Compound @using
In C#, a using statement is used to ensure an object is disposed. In Razor, the same mechanism is used to 
create HTML Helpers that contain additional content. 
In the following code, HTML Helpers render a <form> tag with the @using statement:*@

@using (Html.BeginForm())
{
    <div>
        Email: <input type="email" id="Email" value="Enter Email">
        <button>Register</button>
    </div>
}

PracticeControllerViews/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticeControllerViews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticeControllerViews.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticeControllerViews</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PracticeRazorSyntax" asp-action="Index">Index-method-Of-PracticeRazorSyntax-controller</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PracticeControllerViews - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>